### ISSUE TITLE
[TCEC games db] Cup 4 Bronze match event is incorrect

### ISSUE THREAD

**Issue by skiminki** [TCEC-Chess/tcecgames#12]
The file master-archive/TCEC_Cup_4_Bronze.pgn is actually TCEC Cup 5 bronze match. This is currently incorrect also in the web archive, possibly due to a typo when Cup 5 bronze match was played. Possibly, there this typo then overwrote TCEC Cup 4 bronze match pgn. Fortunately, the correct TCEC Cup 4 Bronze match PGN is still available in the Cup 4 aggregate zip.

**Comment by Aloril** [comment]
Restored. Content was also in individual game pgns TCEC_Cup_4_Bronze_1.pgn etc.. and in game play server.
TCEC_Cup_4_Bronze_Schedule.sjson copied from game server event.json matchProgress and edited tags to match what was in old so should now show games too in GUI.

**Comment by skiminki** [comment]
Reopening. This instance of the bug is intended for the TCEC games database, the other one (#13) was for the web archive. I'll mark it closed when the next release is done.
