### ISSUE TITLE
Cup 4 Bronze match PGN is incorrect (web)

### ISSUE THREAD

**Issue by skiminki** [TCEC-Chess/tcecgames#13]
Both these links currently have the incorrect PGN (Cup 5 Bronze):

- https://tcec-chess.com/archive/json/TCEC_Cup_4_Bronze.pgn
- https://tcec-chess.com/archive/json/TCEC_Cup_4_Bronze.pgn.zip

The correct PGN can still be found in https://tcec-chess.com/archive/json/TCEC_Cup_4_full.pgn.zip .

**Comment by skiminki** [comment]
The related TCEC games db issue is #12.

**Comment by Aloril** [comment]
Fixed when #12 was fixed.
