### ISSUE TITLE
Pgns

### ISSUE THREAD

**Issue by IsaacOkeke** [TCEC-Chess/tcecgames#21]
I would suggest creating a seperate files for the pgn without computer evaluations which would enable one to import into chessbase or several other pgn softwares easily. It seems to occur that if i want to go through the games i have to do input the moves manually because the copy and paste option which inputs the game automatically is not functional because of the other text attachments to the algebraic notation.

**Comment by skiminki** [comment]
That is precisely what the releases are for. Please download TCEC-everything-compact.zip from the latest release in https://github.com/TCEC-Chess/tcecgames/releases/ .
