### ISSUE TITLE
s15glaurung_fritzinbahrain bonus not working

### ISSUE THREAD

**Issue by HansOveL** [TCEC-Chess/tcecgames#4]
Not able to access any games in the s15glaurung_fritzinbahrain bonus event.
Maybe there is some problem with the PGN for this event.

Links like the following one does not load any game https://tcec-chess.com/#div=s15glaurung_fritzinbahrain&game=1&season=bonus  

The problem was detected jjlai1111 when we run the command:
!tdb rnbq1rk1/ppp1ppbp/3p1np1/8/2PP4/2N2NP1/PP2PPBP/R1BQK2R b KQ - 1 6

He noticed that the last link of the output (below) didn't load any game:
tcec-chess.com/#season=bonus&div=s15glaurung_fritzinbahrain&game=96

**Comment by skiminki** [comment]
There seems to be an inconsistency in the Web server PGNs. The zipped event PGN does not exist, but the unzipped does. Maybe this explains the missing games?

- https://tcec-chess.com/archive/json/TCEC_Season_Bonus_-_Division_S15_Glaurung_vs_Fritz_in_Bahrain.pgn.zip (404 not found)
- https://tcec-chess.com/archive/json/TCEC_Season_Bonus_-_Division_S15_Glaurung_vs_Fritz_in_Bahrain.pgn (loads ok)

@Aloril Could you take a look?

**Comment by Aloril** [comment]
Fixed so all of above links should work. Also created somewhat dummy TCEC_Season_Bonus_-_Division_S15_Glaurung_vs_Fritz_in_Bahrain_Schedule.sjson so can list games too. Didn't create cross-table though.

**Comment by skiminki** [comment]
Seems to work, closing
