### ISSUE TITLE
S11 - Division P. Game 269 is missing.

### ISSUE THREAD

**Issue by HansOveL** [TCEC-Chess/tcecgames#5]
S11 - Division P, Games 1-268 load fine.
Game 269 is missing.
Game 270 is loaded with URL https://tcec-chess.com/#div=p&game=269&season=11
Game 271 is loaded with URL https://tcec-chess.com/#div=p&game=270&season=11
Etc.

Looks like the end of game 268 is irregular. It is the only occurrence with a GUI crash. In the pgn Game 268 ends with: 
126. Rc3 {
GUI crash: 6-man EGT adjudication} 1/2-1/2

**Comment by skiminki** [comment]
This looks like it is manually added in the PGN. I would hypothesize that the problem is the following:

```
50. Qg5 { d=28, pd=Rc7, mt=00:00:51, tl=00:09:37, s=23164 kN/s, n=1186191615, pv=Qg5 Rc7 Bg4 Rc3 Bh3 Rf3 Qg4 Rd3, tb=847514, R50=50, wv=-8.42, }
Rc7 { d=36, pd=e7, mt=00:00:37, tl=00:33:17, s=98350 kN/s, n=3700441700, pv=Rc7 e7 Rxe7 Qh6 Qd4 f6 Rf7 Qg6 Qh4+ Kg1 Rc7 Qb1 Qd4+ Kf1 Qd2 f7 Rc1+ Qxc1 Qxc1+ Ke2 Qc2+ Ke1 Qc3+ Kd1 Qf6 Bh5 Qf1+ Kd2 Qxg2+ Ke1 Qe4+ Kf2 Qf4+ Ke1 Qe5+ Be2 Qg3+ Kd1 Qg1+ Kd2 Qg5+ Kc2 Qf5+ Bd3 Qxf7 Kb1 Qxd5 Bc2 Ne7 Kb2 Qe5+ Kb1 Qe1+ Kb2, tb=2484719, R50=50, wv=-18.24, }
51. Bg4 { d=29, pd=Rc3, mt=00:00:45, tl=00:09:02, s=25186 kN/s, n=1139372372, pv=Bg4 Rc3 Bh3 Rf3 Qg4 Rd3 Qg5 Rd1, tb=1101628, R50=49, wv=-9.24,, Black wins by adjudication: TCEC win rule }
0-1


[Event "TCEC Season 11 - Division P"]
[Site "http://tcec.chessdom.com"]
[Date "2018.03.18"]
[Round "67"]
[White "Ginkgo 2.03"]
[Black "Houdini 6.03"]
[Result "1/2-1/2"]
[ECO "D27"]
[WhiteElo "3266"]
[BlackElo "3461"]
[PlyCount "251"]
[EventDate "2018.02.13"]
[TimeControl "5400+10"]
[Termination "adjudication"]
[TerminationDetails "TCEC draw rule"]

{WhiteEngineOptions: Protocol=UCI; Hash=16384; Threads=43; OwnBook=false;
Ponder=false;, BlackEngineOptions: Protocol=UCI; Hash=16384; Threads=43;
```

Notice the two empty lines between the games.

@Aloril Could you take a look at this as well?

**Comment by skiminki** [comment]
The double newline is approx at line 39398

**Comment by skiminki** [comment]
Actually, I missed that G268 ends irregularly. It seems to be missing the termination tag, which is why the GUI displays the game as unterminated in the moves list, even if it says the game is draw in the results. Attached an image.

![image](https://user-images.githubusercontent.com/46296557/145408576-43b80078-566e-450a-bb26-f3f68c4cf34b.png)

**Comment by skiminki** [comment]
In comparison, properly finished games display the "adjudication rule" in the top line results (the above has draw/win counters). This is from another game:

![image](https://user-images.githubusercontent.com/46296557/145409295-64ee91ed-e5cd-47c1-afa3-2f1fb545097c.png)
